# Change these first
owner: advancedcsg-open # Your GitHub organization or username, where this repository lives
repo: toolchain-status-dashboard # The name of this repository

sites:
  - name: Advanced Site without token
    url: https://advancedcsg.atlassian.net/plugins/servlet/ac/advanced-metrics/advanced-metrics-home
  - name: Sonarqube
    url: https://ccq.svc.oneadvanced.com/api/system/status
    __dangerous__body_down_if_text_missing: 'UP'
  - name: Unleash
    url: https://unleash.svc.oneadvanced.com/
  - name: GitHub
    url: https://api.github.com/orgs/advancedcsg

  # GitHub Organisational runners
  - name: adv-cypress-runner-26878
    url: https://api.github.com/orgs/advancedcsg/actions/runners/1135
    __dangerous__body_down_if_text_missing: 'online'
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-type: application/vnd.github+json"
      - "X-GitHub-Api-Version: 2022-11-28"
  - name: CMISGO
    url: https://api.github.com/orgs/advancedcsg/actions/runners/44
    __dangerous__body_down_if_text_missing: 'online'
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-type: application/vnd.github+json"
      - "X-GitHub-Api-Version: 2022-11-28"
  - name: WIN-8I19VLCBLTQ
    url: https://api.github.com/orgs/advancedcsg/actions/runners/37
    __dangerous__body_down_if_text_missing: 'online'
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-type: application/vnd.github+json"
      - "X-GitHub-Api-Version: 2022-11-28"
  - name: ALB-GithubRunner
    url: https://api.github.com/orgs/advancedcsg/actions/runners/57
    __dangerous__body_down_if_text_missing: 'online'
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-type: application/vnd.github+json"
      - "X-GitHub-Api-Version: 2022-11-28"
  - name: adv-compass-pmdevel
    url: https://api.github.com/orgs/advancedcsg/actions/runners/310
    __dangerous__body_down_if_text_missing: 'online'
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-type: application/vnd.github+json"
      - "X-GitHub-Api-Version: 2022-11-28"
  - name: adv-cypress-runner-32442
    url: https://api.github.com/orgs/advancedcsg/actions/runners/853
    __dangerous__body_down_if_text_missing: 'online'
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-type: application/vnd.github+json"
      - "X-GitHub-Api-Version: 2022-11-28"
  - name: advancedcsg-self-hosted-runner-zrvln-qjlf8
    url: https://api.github.com/orgs/advancedcsg/actions/runners/1592
    __dangerous__body_down_if_text_missing: 'online'
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-type: application/vnd.github+json"
      - "X-GitHub-Api-Version: 2022-11-28"
  - name: adv-cypress-runner-13963
    url: https://api.github.com/orgs/advancedcsg/actions/runners/1136
    __dangerous__body_down_if_text_missing: 'online'
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-type: application/vnd.github+json"
      - "X-GitHub-Api-Version: 2022-11-28"
  - name: adv-cypress-runner-20878
    url: https://api.github.com/orgs/advancedcsg/actions/runners/1138
    __dangerous__body_down_if_text_missing: 'online'
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-type: application/vnd.github+json"
      - "X-GitHub-Api-Version: 2022-11-28"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: demo.upptime.js.org
  baseUrl: /toolchain-status-dashboard
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Toolchain status dashboard"
  introMessage: Status dashboard page of all the tools handled by G&T Team
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
